///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LynxDrive_ControlSystems_001
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LynxDrive_ControlSystems_001Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
    public partial class LynxDrive_ControlSystems_001Repository : RepoGenBaseFolder
    {
        static LynxDrive_ControlSystems_001Repository instance = new LynxDrive_ControlSystems_001Repository();
        LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder _cs_hublevel;
        LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder _cs_dblevel;
        LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder _cs_stalevel;

        /// <summary>
        /// Gets the singleton class instance representing the LynxDrive_ControlSystems_001Repository element repository.
        /// </summary>
        [RepositoryFolder("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
        public static LynxDrive_ControlSystems_001Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LynxDrive_ControlSystems_001Repository() 
            : base("LynxDrive_ControlSystems_001Repository", "/", null, 0, false, "e8ed7e89-4d41-4e82-9a50-cc271cb89461", ".\\RepositoryImages\\LynxDrive_ControlSystems_001Repositorye8ed7e89.rximgres")
        {
            _cs_hublevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder(this);
            _cs_dblevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder(this);
            _cs_stalevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CS_HubLevel folder.
        /// </summary>
        [RepositoryFolder("b983c49d-58bb-4543-b266-de857dc45f86")]
        public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder CS_HubLevel
        {
            get { return _cs_hublevel; }
        }

        /// <summary>
        /// The CS_DBLevel folder.
        /// </summary>
        [RepositoryFolder("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
        public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder CS_DBLevel
        {
            get { return _cs_dblevel; }
        }

        /// <summary>
        /// The CS_StaLevel folder.
        /// </summary>
        [RepositoryFolder("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
        public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder CS_StaLevel
        {
            get { return _cs_stalevel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LynxDrive_ControlSystems_001RepositoryFolders
    {
        /// <summary>
        /// The CS_HubLevelFolder folder.
        /// </summary>
        [RepositoryFolder("b983c49d-58bb-4543-b266-de857dc45f86")]
        public partial class CS_HubLevelFolder : RepoGenBaseFolder
        {
            LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder _mainform;
            LynxDrive_ControlSystems_001RepositoryFolders.Comm_SelectFolder _comm_select;

            /// <summary>
            /// Creates a new CS_HubLevel  folder.
            /// </summary>
            public CS_HubLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_HubLevel", "", parentFolder, 0, null, false, "b983c49d-58bb-4543-b266-de857dc45f86", "")
            {
                _mainform = new LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder(this);
                _comm_select = new LynxDrive_ControlSystems_001RepositoryFolders.Comm_SelectFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b983c49d-58bb-4543-b266-de857dc45f86")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainForm folder.
            /// </summary>
            [RepositoryFolder("802bab65-8203-43d5-8d40-56e854c7c07a")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder MainForm
            {
                get { return _mainform; }
            }

            /// <summary>
            /// The Comm_Select folder.
            /// </summary>
            [RepositoryFolder("ccaff60e-22db-4b13-8cc9-4561e3ee0119")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.Comm_SelectFolder Comm_Select
            {
                get { return _comm_select; }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("802bab65-8203-43d5-8d40-56e854c7c07a")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _smarthubrow1Info;
            RepoItemInfo _status1row1Info;
            RepoItemInfo _status2row1Info;
            RepoItemInfo _navigaterow1Info;
            RepoItemInfo _namerow1Info;
            RepoItemInfo _enabledstationsrow1Info;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "802bab65-8203-43d5-8d40-56e854c7c07a", "")
            {
                _smarthubrow1Info = new RepoItemInfo(this, "SmartHubRow1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Smart Hub row 1']", ".//cell[@accessiblename='Smart Hub row 1']", 30000, null, "5679f5ef-e681-46fc-9a21-22a128a461e7");
                _status1row1Info = new RepoItemInfo(this, "Status1Row1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Status1 row 1']", ".//cell[@accessiblename='Status1 row 1']", 30000, null, "e748eb92-9f28-45c1-8fd3-e569117c86aa");
                _status2row1Info = new RepoItemInfo(this, "Status2Row1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Status2 row 1']", ".//cell[@accessiblename='Status2 row 1']", 30000, null, "f82f2ab7-2a90-43ff-ad7d-f457054ca4cf");
                _navigaterow1Info = new RepoItemInfo(this, "NavigateRow1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Navigate row 1']", ".//cell[@accessiblename='Navigate row 1']", 30000, null, "1b565cac-9444-407c-b499-85ea639bfd50");
                _namerow1Info = new RepoItemInfo(this, "NameRow1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Name row 1']", ".//cell[@accessiblename='Name row 1']", 30000, null, "d44dc902-ce98-436a-911e-308b6c008c38");
                _enabledstationsrow1Info = new RepoItemInfo(this, "EnabledStationsRow1", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Enabled Stations row 1']", ".//cell[@accessiblename='Enabled Stations row 1']", 30000, null, "10aa3498-a977-46b7-bb10-ca8d965f2320");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("802bab65-8203-43d5-8d40-56e854c7c07a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("802bab65-8203-43d5-8d40-56e854c7c07a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SmartHubRow1 item.
            /// </summary>
            [RepositoryItem("5679f5ef-e681-46fc-9a21-22a128a461e7")]
            public virtual Ranorex.Cell SmartHubRow1
            {
                get
                {
                    return _smarthubrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SmartHubRow1 item info.
            /// </summary>
            [RepositoryItemInfo("5679f5ef-e681-46fc-9a21-22a128a461e7")]
            public virtual RepoItemInfo SmartHubRow1Info
            {
                get
                {
                    return _smarthubrow1Info;
                }
            }

            /// <summary>
            /// The Status1Row1 item.
            /// </summary>
            [RepositoryItem("e748eb92-9f28-45c1-8fd3-e569117c86aa")]
            public virtual Ranorex.Cell Status1Row1
            {
                get
                {
                    return _status1row1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Status1Row1 item info.
            /// </summary>
            [RepositoryItemInfo("e748eb92-9f28-45c1-8fd3-e569117c86aa")]
            public virtual RepoItemInfo Status1Row1Info
            {
                get
                {
                    return _status1row1Info;
                }
            }

            /// <summary>
            /// The Status2Row1 item.
            /// </summary>
            [RepositoryItem("f82f2ab7-2a90-43ff-ad7d-f457054ca4cf")]
            public virtual Ranorex.Cell Status2Row1
            {
                get
                {
                    return _status2row1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Status2Row1 item info.
            /// </summary>
            [RepositoryItemInfo("f82f2ab7-2a90-43ff-ad7d-f457054ca4cf")]
            public virtual RepoItemInfo Status2Row1Info
            {
                get
                {
                    return _status2row1Info;
                }
            }

            /// <summary>
            /// The NavigateRow1 item.
            /// </summary>
            [RepositoryItem("1b565cac-9444-407c-b499-85ea639bfd50")]
            public virtual Ranorex.Cell NavigateRow1
            {
                get
                {
                    return _navigaterow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NavigateRow1 item info.
            /// </summary>
            [RepositoryItemInfo("1b565cac-9444-407c-b499-85ea639bfd50")]
            public virtual RepoItemInfo NavigateRow1Info
            {
                get
                {
                    return _navigaterow1Info;
                }
            }

            /// <summary>
            /// The NameRow1 item.
            /// </summary>
            [RepositoryItem("d44dc902-ce98-436a-911e-308b6c008c38")]
            public virtual Ranorex.Cell NameRow1
            {
                get
                {
                    return _namerow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow1 item info.
            /// </summary>
            [RepositoryItemInfo("d44dc902-ce98-436a-911e-308b6c008c38")]
            public virtual RepoItemInfo NameRow1Info
            {
                get
                {
                    return _namerow1Info;
                }
            }

            /// <summary>
            /// The EnabledStationsRow1 item.
            /// </summary>
            [RepositoryItem("10aa3498-a977-46b7-bb10-ca8d965f2320")]
            public virtual Ranorex.Cell EnabledStationsRow1
            {
                get
                {
                    return _enabledstationsrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The EnabledStationsRow1 item info.
            /// </summary>
            [RepositoryItemInfo("10aa3498-a977-46b7-bb10-ca8d965f2320")]
            public virtual RepoItemInfo EnabledStationsRow1Info
            {
                get
                {
                    return _enabledstationsrow1Info;
                }
            }
        }

        /// <summary>
        /// The Comm_SelectFolder folder.
        /// </summary>
        [RepositoryFolder("ccaff60e-22db-4b13-8cc9-4561e3ee0119")]
        public partial class Comm_SelectFolder : RepoGenBaseFolder
        {
            LynxDrive_ControlSystems_001RepositoryFolders.LynxClientAppFolder _lynxclient;
            RepoItemInfo _linkrow1Info;
            RepoItemInfo _openInfo;

            /// <summary>
            /// Creates a new Comm_Select  folder.
            /// </summary>
            public Comm_SelectFolder(RepoGenBaseFolder parentFolder) :
                    base("Comm_Select", "", parentFolder, 0, null, false, "ccaff60e-22db-4b13-8cc9-4561e3ee0119", "")
            {
                _lynxclient = new LynxDrive_ControlSystems_001RepositoryFolders.LynxClientAppFolder(this);
                _linkrow1Info = new RepoItemInfo(this, "LinkRow1", "/form[@controlname='MainForm']/container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/?/?/listitem[@accessiblename='Row 1']/cell[@accessiblename='Link row 1']", "/form[@controlname='MainForm']//cell[@accessiblename='Link row 1']", 30000, null, "904273e2-f2c8-4ae4-ab81-dd7b09adaefa");
                _openInfo = new RepoItemInfo(this, "Open", "/form[@controlname='MainForm']/container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/?/?/grip[@controlname='<Panel1>k__BackingField']/?/?/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/?/?/combobox[@accessiblename='Editing control']/button[@accessiblename='Open']", "/form[@controlname='MainForm']//button[@accessiblename='Open']", 30000, null, "632fc51e-60cd-4508-8219-d271159013d6");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccaff60e-22db-4b13-8cc9-4561e3ee0119")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LinkRow1 item.
            /// </summary>
            [RepositoryItem("904273e2-f2c8-4ae4-ab81-dd7b09adaefa")]
            public virtual Ranorex.Cell LinkRow1
            {
                get
                {
                    return _linkrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The LinkRow1 item info.
            /// </summary>
            [RepositoryItemInfo("904273e2-f2c8-4ae4-ab81-dd7b09adaefa")]
            public virtual RepoItemInfo LinkRow1Info
            {
                get
                {
                    return _linkrow1Info;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("632fc51e-60cd-4508-8219-d271159013d6")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("632fc51e-60cd-4508-8219-d271159013d6")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The LynxClient folder.
            /// </summary>
            [RepositoryFolder("e1f1b252-fbad-4b81-9a23-08bb7c90a7d3")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.LynxClientAppFolder LynxClient
            {
                get { return _lynxclient; }
            }
        }

        /// <summary>
        /// The LynxClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("e1f1b252-fbad-4b81-9a23-08bb7c90a7d3")]
        public partial class LynxClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _wirelink1unassignedInfo;

            /// <summary>
            /// Creates a new LynxClient  folder.
            /// </summary>
            public LynxClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LynxClient", "/form[@title='']", parentFolder, 30000, null, true, "e1f1b252-fbad-4b81-9a23-08bb7c90a7d3", "")
            {
                _wirelink1unassignedInfo = new RepoItemInfo(this, "WIRELINK1Unassigned", "?/?/list[@accessiblename='']/listitem[@accessiblename='WIRELINK1 (Unassigned)']", ".//listitem[@accessiblename='WIRELINK1 (Unassigned)']", 30000, null, "2b1682f4-04e6-4f48-9271-26220142aad5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e1f1b252-fbad-4b81-9a23-08bb7c90a7d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e1f1b252-fbad-4b81-9a23-08bb7c90a7d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WIRELINK1Unassigned item.
            /// </summary>
            [RepositoryItem("2b1682f4-04e6-4f48-9271-26220142aad5")]
            public virtual Ranorex.ListItem WIRELINK1Unassigned
            {
                get
                {
                    return _wirelink1unassignedInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The WIRELINK1Unassigned item info.
            /// </summary>
            [RepositoryItemInfo("2b1682f4-04e6-4f48-9271-26220142aad5")]
            public virtual RepoItemInfo WIRELINK1UnassignedInfo
            {
                get
                {
                    return _wirelink1unassignedInfo;
                }
            }
        }

        /// <summary>
        /// The CS_DBLevelFolder folder.
        /// </summary>
        [RepositoryFolder("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
        public partial class CS_DBLevelFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CS_DBLevel  folder.
            /// </summary>
            public CS_DBLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_DBLevel", "", parentFolder, 0, null, false, "ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CS_StaLevelFolder folder.
        /// </summary>
        [RepositoryFolder("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
        public partial class CS_StaLevelFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CS_StaLevel  folder.
            /// </summary>
            public CS_StaLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_StaLevel", "", parentFolder, 0, null, false, "f8c3bdb5-4842-4630-b9be-00f1fa85e056", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
