///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LynxDrive_ControlSystems_001
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LynxDrive_ControlSystems_001Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
    public partial class LynxDrive_ControlSystems_001Repository : RepoGenBaseFolder
    {
        static LynxDrive_ControlSystems_001Repository instance = new LynxDrive_ControlSystems_001Repository();
        LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder _mainform;
        LynxDrive_ControlSystems_001RepositoryFolders.FormMainAppFolder _formmain;

        /// <summary>
        /// Gets the singleton class instance representing the LynxDrive_ControlSystems_001Repository element repository.
        /// </summary>
        [RepositoryFolder("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
        public static LynxDrive_ControlSystems_001Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LynxDrive_ControlSystems_001Repository() 
            : base("LynxDrive_ControlSystems_001Repository", "/", null, 0, false, "e8ed7e89-4d41-4e82-9a50-cc271cb89461", ".\\RepositoryImages\\LynxDrive_ControlSystems_001Repositorye8ed7e89.rximgres")
        {
            _mainform = new LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder(this);
            _formmain = new LynxDrive_ControlSystems_001RepositoryFolders.FormMainAppFolder(this);
        }

#region Variables

        string _StationValue = "1-1-1";

        /// <summary>
        /// Gets or sets the value of variable StationValue.
        /// </summary>
        [TestVariable("77bdd520-64cd-46be-a2e2-dc851795f7bd")]
        public string StationValue
        {
            get { return _StationValue; }
            set { _StationValue = value; }
        }

        string _StationRowName = "Station row 1";

        /// <summary>
        /// Gets or sets the value of variable StationRowName.
        /// </summary>
        [TestVariable("a4e91265-a12c-4215-bde2-acad0df40c23")]
        public string StationRowName
        {
            get { return _StationRowName; }
            set { _StationRowName = value; }
        }

        string _StationAccessRow = "Row 1";

        /// <summary>
        /// Gets or sets the value of variable StationAccessRow.
        /// </summary>
        [TestVariable("898adc18-b057-4177-8a0e-754df65b9419")]
        public string StationAccessRow
        {
            get { return _StationAccessRow; }
            set { _StationAccessRow = value; }
        }

        string _NameRow = "Name row 1";

        /// <summary>
        /// Gets or sets the value of variable NameRow.
        /// </summary>
        [TestVariable("07066385-055b-4be8-a01e-c1e9f82842c4")]
        public string NameRow
        {
            get { return _NameRow; }
            set { _NameRow = value; }
        }

        string _AreaRowName = "Area row 1";

        /// <summary>
        /// Gets or sets the value of variable AreaRowName.
        /// </summary>
        [TestVariable("141718b8-68d4-4a5a-ab7e-93bdd41d190a")]
        public string AreaRowName
        {
            get { return _AreaRowName; }
            set { _AreaRowName = value; }
        }

        string _HoleRowName = "Hole row 1";

        /// <summary>
        /// Gets or sets the value of variable HoleRowName.
        /// </summary>
        [TestVariable("5858e01a-02b5-438b-ae94-d1a9df8c7031")]
        public string HoleRowName
        {
            get { return _HoleRowName; }
            set { _HoleRowName = value; }
        }

        string _TagRowName = "Tag row 1";

        /// <summary>
        /// Gets or sets the value of variable TagRowName.
        /// </summary>
        [TestVariable("8287f9e7-c863-4c14-a72f-753d261041b5")]
        public string TagRowName
        {
            get { return _TagRowName; }
            set { _TagRowName = value; }
        }

        string _NOSRowName = "Number of Sprinklers row";

        /// <summary>
        /// Gets or sets the value of variable NOSRowName.
        /// </summary>
        [TestVariable("bc7f217f-b88a-40b9-bd85-5cd8cb54463b")]
        public string NOSRowName
        {
            get { return _NOSRowName; }
            set { _NOSRowName = value; }
        }

        string _AddRowName = "LSMAddress row 1";

        /// <summary>
        /// Gets or sets the value of variable AddRowName.
        /// </summary>
        [TestVariable("0d76ec27-31fa-4f97-827f-334f6c7c7d43")]
        public string AddRowName
        {
            get { return _AddRowName; }
            set { _AddRowName = value; }
        }

        string _OffsetRowName = "LSMOffset row 1";

        /// <summary>
        /// Gets or sets the value of variable OffsetRowName.
        /// </summary>
        [TestVariable("787b90f2-d2d3-462c-a002-3d0b686e34e9")]
        public string OffsetRowName
        {
            get { return _OffsetRowName; }
            set { _OffsetRowName = value; }
        }

        string _WPRowName = "Wire Path row 1";

        /// <summary>
        /// Gets or sets the value of variable WPRowName.
        /// </summary>
        [TestVariable("26e7a50c-7c1f-45e9-8726-8474123b75f4")]
        public string WPRowName
        {
            get { return _WPRowName; }
            set { _WPRowName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8ed7e89-4d41-4e82-9a50-cc271cb89461")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("802bab65-8203-43d5-8d40-56e854c7c07a")]
        public virtual LynxDrive_ControlSystems_001RepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The FormMain folder.
        /// </summary>
        [RepositoryFolder("f640f73a-3c69-4234-a594-c821f9927dae")]
        public virtual LynxDrive_ControlSystems_001RepositoryFolders.FormMainAppFolder FormMain
        {
            get { return _formmain; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LynxDrive_ControlSystems_001RepositoryFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("802bab65-8203-43d5-8d40-56e854c7c07a")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder _cs_stalevel;
            LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder _cs_hublevel;
            LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder _cs_dblevel;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "802bab65-8203-43d5-8d40-56e854c7c07a", "")
            {
                _cs_stalevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder(this);
                _cs_hublevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder(this);
                _cs_dblevel = new LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("802bab65-8203-43d5-8d40-56e854c7c07a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("802bab65-8203-43d5-8d40-56e854c7c07a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CS_StaLevel folder.
            /// </summary>
            [RepositoryFolder("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_StaLevelFolder CS_StaLevel
            {
                get { return _cs_stalevel; }
            }

            /// <summary>
            /// The CS_HubLevel folder.
            /// </summary>
            [RepositoryFolder("b983c49d-58bb-4543-b266-de857dc45f86")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_HubLevelFolder CS_HubLevel
            {
                get { return _cs_hublevel; }
            }

            /// <summary>
            /// The CS_DBLevel folder.
            /// </summary>
            [RepositoryFolder("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.CS_DBLevelFolder CS_DBLevel
            {
                get { return _cs_dblevel; }
            }
        }

        /// <summary>
        /// The CS_StaLevelFolder folder.
        /// </summary>
        [RepositoryFolder("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
        public partial class CS_StaLevelFolder : RepoGenBaseFolder
        {
            LynxDrive_ControlSystems_001RepositoryFolders.SidePanelFolder _sidepanel;
            RepoItemInfo _rstationrowInfo;
            RepoItemInfo _rnamerowInfo;
            RepoItemInfo _rarearowInfo;
            RepoItemInfo _rholerowInfo;
            RepoItemInfo _rtagrowInfo;
            RepoItemInfo _rnosrowInfo;
            RepoItemInfo _rlsmaddressrowInfo;
            RepoItemInfo _rlsmoffsetrowInfo;
            RepoItemInfo _rwirepathrowInfo;

            /// <summary>
            /// Creates a new CS_StaLevel  folder.
            /// </summary>
            public CS_StaLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_StaLevel", "", parentFolder, 0, null, false, "f8c3bdb5-4842-4630-b9be-00f1fa85e056", "")
            {
                _sidepanel = new LynxDrive_ControlSystems_001RepositoryFolders.SidePanelFolder(this);
                _rstationrowInfo = new RepoItemInfo(this, "rStationRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$StationRowName and @accessiblevalue=$StationValue]", "", 30000, null, "da8185ec-bdc7-4db9-8037-1c16a69058af");
                _rnamerowInfo = new RepoItemInfo(this, "rNameRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$NameRow]", "", 30000, null, "1ea7a6aa-4a78-40ae-850b-6f3005b4e7d2");
                _rarearowInfo = new RepoItemInfo(this, "rAreaRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$AreaRowName]", "", 30000, null, "3a2f91ef-1f38-4714-8b7a-f20377ef85b6");
                _rholerowInfo = new RepoItemInfo(this, "rHoleRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$HoleRowName]", "", 30000, null, "083be34a-caf6-4d0d-99c9-cd05413e2311");
                _rtagrowInfo = new RepoItemInfo(this, "rTagRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$TagRowName]", "", 30000, null, "644f57ed-d253-44d1-993f-65df96cae57e");
                _rnosrowInfo = new RepoItemInfo(this, "rNOSRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename>$NOSRowName]", "", 30000, null, "9714ce46-ded0-4d83-8a41-7f7cbadb58dd");
                _rlsmaddressrowInfo = new RepoItemInfo(this, "rLSMAddressRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$AddRowName]", "", 30000, null, "37f707f1-525b-4106-8e65-883be8fe0fda");
                _rlsmoffsetrowInfo = new RepoItemInfo(this, "rLSMOffsetRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$OffsetRowName]", "", 30000, null, "408175bd-c0ee-49ee-9035-349d20be6306");
                _rwirepathrowInfo = new RepoItemInfo(this, "rWirePathRow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspace']/container[@controlname='workspaceSplitter']/grip[@controlname='<Panel1>k__BackingField']/container[@controlname='workspacePanel']/container[@controlname='ControlSystemWorkspace']/element[@controlname='grid']/table[@accessiblename='MainView']/container[@accessiblename='Data Panel']/listitem[@accessiblename=$StationAccessRow]/cell[@accessiblename=$WPRowName]", "", 30000, null, "64a4749c-c186-4937-bea1-7bddcda93664");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8c3bdb5-4842-4630-b9be-00f1fa85e056")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rStationRow item.
            /// </summary>
            [RepositoryItem("da8185ec-bdc7-4db9-8037-1c16a69058af")]
            public virtual Ranorex.Cell rStationRow
            {
                get
                {
                    return _rstationrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rStationRow item info.
            /// </summary>
            [RepositoryItemInfo("da8185ec-bdc7-4db9-8037-1c16a69058af")]
            public virtual RepoItemInfo rStationRowInfo
            {
                get
                {
                    return _rstationrowInfo;
                }
            }

            /// <summary>
            /// The rNameRow item.
            /// </summary>
            [RepositoryItem("1ea7a6aa-4a78-40ae-850b-6f3005b4e7d2")]
            public virtual Ranorex.Cell rNameRow
            {
                get
                {
                    return _rnamerowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rNameRow item info.
            /// </summary>
            [RepositoryItemInfo("1ea7a6aa-4a78-40ae-850b-6f3005b4e7d2")]
            public virtual RepoItemInfo rNameRowInfo
            {
                get
                {
                    return _rnamerowInfo;
                }
            }

            /// <summary>
            /// The rAreaRow item.
            /// </summary>
            [RepositoryItem("3a2f91ef-1f38-4714-8b7a-f20377ef85b6")]
            public virtual Ranorex.Cell rAreaRow
            {
                get
                {
                    return _rarearowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rAreaRow item info.
            /// </summary>
            [RepositoryItemInfo("3a2f91ef-1f38-4714-8b7a-f20377ef85b6")]
            public virtual RepoItemInfo rAreaRowInfo
            {
                get
                {
                    return _rarearowInfo;
                }
            }

            /// <summary>
            /// The rHoleRow item.
            /// </summary>
            [RepositoryItem("083be34a-caf6-4d0d-99c9-cd05413e2311")]
            public virtual Ranorex.Cell rHoleRow
            {
                get
                {
                    return _rholerowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rHoleRow item info.
            /// </summary>
            [RepositoryItemInfo("083be34a-caf6-4d0d-99c9-cd05413e2311")]
            public virtual RepoItemInfo rHoleRowInfo
            {
                get
                {
                    return _rholerowInfo;
                }
            }

            /// <summary>
            /// The rTagRow item.
            /// </summary>
            [RepositoryItem("644f57ed-d253-44d1-993f-65df96cae57e")]
            public virtual Ranorex.Cell rTagRow
            {
                get
                {
                    return _rtagrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rTagRow item info.
            /// </summary>
            [RepositoryItemInfo("644f57ed-d253-44d1-993f-65df96cae57e")]
            public virtual RepoItemInfo rTagRowInfo
            {
                get
                {
                    return _rtagrowInfo;
                }
            }

            /// <summary>
            /// The rNOSRow item.
            /// </summary>
            [RepositoryItem("9714ce46-ded0-4d83-8a41-7f7cbadb58dd")]
            public virtual Ranorex.Cell rNOSRow
            {
                get
                {
                    return _rnosrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rNOSRow item info.
            /// </summary>
            [RepositoryItemInfo("9714ce46-ded0-4d83-8a41-7f7cbadb58dd")]
            public virtual RepoItemInfo rNOSRowInfo
            {
                get
                {
                    return _rnosrowInfo;
                }
            }

            /// <summary>
            /// The rLSMAddressRow item.
            /// </summary>
            [RepositoryItem("37f707f1-525b-4106-8e65-883be8fe0fda")]
            public virtual Ranorex.Cell rLSMAddressRow
            {
                get
                {
                    return _rlsmaddressrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rLSMAddressRow item info.
            /// </summary>
            [RepositoryItemInfo("37f707f1-525b-4106-8e65-883be8fe0fda")]
            public virtual RepoItemInfo rLSMAddressRowInfo
            {
                get
                {
                    return _rlsmaddressrowInfo;
                }
            }

            /// <summary>
            /// The rLSMOffsetRow item.
            /// </summary>
            [RepositoryItem("408175bd-c0ee-49ee-9035-349d20be6306")]
            public virtual Ranorex.Cell rLSMOffsetRow
            {
                get
                {
                    return _rlsmoffsetrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rLSMOffsetRow item info.
            /// </summary>
            [RepositoryItemInfo("408175bd-c0ee-49ee-9035-349d20be6306")]
            public virtual RepoItemInfo rLSMOffsetRowInfo
            {
                get
                {
                    return _rlsmoffsetrowInfo;
                }
            }

            /// <summary>
            /// The rWirePathRow item.
            /// </summary>
            [RepositoryItem("64a4749c-c186-4937-bea1-7bddcda93664")]
            public virtual Ranorex.Cell rWirePathRow
            {
                get
                {
                    return _rwirepathrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The rWirePathRow item info.
            /// </summary>
            [RepositoryItemInfo("64a4749c-c186-4937-bea1-7bddcda93664")]
            public virtual RepoItemInfo rWirePathRowInfo
            {
                get
                {
                    return _rwirepathrowInfo;
                }
            }

            /// <summary>
            /// The SidePanel folder.
            /// </summary>
            [RepositoryFolder("8d836c97-baf3-4411-b52c-dc9a40c04586")]
            public virtual LynxDrive_ControlSystems_001RepositoryFolders.SidePanelFolder SidePanel
            {
                get { return _sidepanel; }
            }
        }

        /// <summary>
        /// The SidePanelFolder folder.
        /// </summary>
        [RepositoryFolder("8d836c97-baf3-4411-b52c-dc9a40c04586")]
        public partial class SidePanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rsidepanelscrollbarInfo;
            RepoItemInfo _rsprinklermodelInfo;
            RepoItemInfo _rnozzlemodelInfo;
            RepoItemInfo _rarcInfo;
            RepoItemInfo _rpressureInfo;
            RepoItemInfo _rnumsprinklersInfo;
            RepoItemInfo _rnozzleflowInfo;
            RepoItemInfo _rbackflowInfo;
            RepoItemInfo _rstaflowInfo;
            RepoItemInfo _rpreciprateInfo;
            RepoItemInfo _rpatternInfo;
            RepoItemInfo _rsprinklerspacingInfo;
            RepoItemInfo _rrowspacingInfo;

            /// <summary>
            /// Creates a new SidePanel  folder.
            /// </summary>
            public SidePanelFolder(RepoGenBaseFolder parentFolder) :
                    base("SidePanel", "", parentFolder, 0, null, false, "8d836c97-baf3-4411-b52c-dc9a40c04586", "")
            {
                _rsidepanelscrollbarInfo = new RepoItemInfo(this, "rSidePanelScrollBar", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']", ".//container[@controlname='stackPanel']", 30000, null, "175b26d9-3bfb-4529-b516-2c0896879aac");
                _rsprinklermodelInfo = new RepoItemInfo(this, "rSprinklerModel", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='1']/container[@controlname='lynxPanel']/container[@controlname='cpSprinklerModel']/container[@controlname='tableLayoutPanel1']/text[@controlname='comboBoxEdit']/combobox[@accessiblerole='ComboBox']", ".//text[@controltypename='TextBox' and @instance='1' and @controltext='730']/combobox[@accessiblerole='ComboBox']", 30000, null, "abc3e607-0025-4f65-a47d-d455b127bd6c");
                _rnozzlemodelInfo = new RepoItemInfo(this, "rNozzleModel", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='1']/container[@controlname='lynxPanel']/container[@controlname='cpNozzleModel']/container[@controlname='tableLayoutPanel1']/text[@controlname='comboBoxEdit']/combobox[@accessiblerole='ComboBox']", ".//combobox[@accessiblerole='ComboBox']", 30000, null, "11cb1423-6f1f-45ee-bb3f-23d3a3f9d257");
                _rarcInfo = new RepoItemInfo(this, "rArc", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='1']/container[@controlname='lynxPanel']/container[@controlname='npArc']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controltypename='TextBox' and @instance='0' and @controltext='360']/text[@controltypename='TextBox']", 30000, null, "0ac9611d-31d2-4764-802c-1e47284a334a");
                _rpressureInfo = new RepoItemInfo(this, "rPressure", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='1']/container[@controlname='lynxPanel']/container[@controlname='npPressure']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controlname='numericEdit']/text[@controltypename='TextBox']", 30000, null, "9f54a3fa-0684-4cef-86f6-58c02cb35f83");
                _rnumsprinklersInfo = new RepoItemInfo(this, "rNumSprinklers", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='2']/container[@controlname='lynxPanel']/container[@controlname='npSprinklerCount']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controltypename='TextBox' and @instance='0' and @controltext='1']/text[@controltypename='TextBox']", 30000, null, "f270bdcd-4106-4eee-b92c-b8b5a7b913a7");
                _rnozzleflowInfo = new RepoItemInfo(this, "rNozzleFlow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='2']/container[@controlname='lynxPanel']/container[@controlname='npNozzleFlow']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//container[@controlname='npNozzleFlow']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", 30000, null, "21354700-b26d-4efe-8fa4-702b4d6bd5d9");
                _rbackflowInfo = new RepoItemInfo(this, "rBackFlow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='2']/container[@controlname='lynxPanel']/container[@controlname='npBackFlow']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controltypename='TextBox' and @instance='0' and @controltext='0']/text[@controltypename='TextBox']", 30000, null, "7dc6ad49-f63e-411e-815c-3d9f58beaeaa");
                _rstaflowInfo = new RepoItemInfo(this, "rStaFlow", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='2']/container[@controlname='lynxPanel']/container[@controlname='npStationFlow']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controltypename='TextBox' and @instance='0' and @controltext='22']/text[@controltypename='TextBox']", 30000, null, "3a43408b-938d-4379-9b7f-375b0ca8e93f");
                _rpreciprateInfo = new RepoItemInfo(this, "rPrecipRate", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='2']/container[@controlname='lynxPanel']/container[@controlname='npPrecipRate']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//text[@controltypename='TextBox' and @instance='0' and @controltext='0.57']/text[@controltypename='TextBox']", 30000, null, "c765f2ad-47a6-4a61-84e2-0f474ae2f32a");
                _rpatternInfo = new RepoItemInfo(this, "rPattern", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='3']/container[@controlname='lynxPanel']/container[@controlname='cpPattern']/container[@controlname='tableLayoutPanel1']/text[@controlname='comboBoxEdit']/combobox[@accessiblerole='ComboBox']", ".//text[@controltypename='TextBox' and @instance='1' and @controltext='Triangle']/combobox[@accessiblerole='ComboBox']", 30000, null, "56b7ea5a-b999-402f-b862-4ab2e9849598");
                _rsprinklerspacingInfo = new RepoItemInfo(this, "rSprinklerSpacing", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='3']/container[@controlname='lynxPanel']/container[@controlname='npSprinklerSpacing']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//container[@controlname='npSprinklerSpacing']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", 30000, null, "f120039d-2ced-4585-82dc-7f86d020c9a1");
                _rrowspacingInfo = new RepoItemInfo(this, "rRowSpacing", "container[@controlname='secondaryPanel']/container[@controlname='detailSplitter']/grip[@controlname='<Panel2>k__BackingField']/container[@controlname='detailPanel']/container[@controlname='stackPanel']/container[@caption='' and @controltypename='ScrollableControl' and @instance='3']/container[@controlname='lynxPanel']/container[@controlname='npRowSpacing']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", ".//container[@controlname='npRowSpacing']/container[@controlname='tableLayoutPanel1']/container[@controlname='panel1']/text[@controlname='numericEdit']/text[@controltypename='TextBox']", 30000, null, "a96d516f-0934-402b-abb4-f15ca99f5722");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d836c97-baf3-4411-b52c-dc9a40c04586")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rSidePanelScrollBar item.
            /// </summary>
            [RepositoryItem("175b26d9-3bfb-4529-b516-2c0896879aac")]
            public virtual Ranorex.Container rSidePanelScrollBar
            {
                get
                {
                    return _rsidepanelscrollbarInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The rSidePanelScrollBar item info.
            /// </summary>
            [RepositoryItemInfo("175b26d9-3bfb-4529-b516-2c0896879aac")]
            public virtual RepoItemInfo rSidePanelScrollBarInfo
            {
                get
                {
                    return _rsidepanelscrollbarInfo;
                }
            }

            /// <summary>
            /// The rSprinklerModel item.
            /// </summary>
            [RepositoryItem("abc3e607-0025-4f65-a47d-d455b127bd6c")]
            public virtual Ranorex.ComboBox rSprinklerModel
            {
                get
                {
                    return _rsprinklermodelInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The rSprinklerModel item info.
            /// </summary>
            [RepositoryItemInfo("abc3e607-0025-4f65-a47d-d455b127bd6c")]
            public virtual RepoItemInfo rSprinklerModelInfo
            {
                get
                {
                    return _rsprinklermodelInfo;
                }
            }

            /// <summary>
            /// The rNozzleModel item.
            /// </summary>
            [RepositoryItem("11cb1423-6f1f-45ee-bb3f-23d3a3f9d257")]
            public virtual Ranorex.ComboBox rNozzleModel
            {
                get
                {
                    return _rnozzlemodelInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The rNozzleModel item info.
            /// </summary>
            [RepositoryItemInfo("11cb1423-6f1f-45ee-bb3f-23d3a3f9d257")]
            public virtual RepoItemInfo rNozzleModelInfo
            {
                get
                {
                    return _rnozzlemodelInfo;
                }
            }

            /// <summary>
            /// The rArc item.
            /// </summary>
            [RepositoryItem("0ac9611d-31d2-4764-802c-1e47284a334a")]
            public virtual Ranorex.Text rArc
            {
                get
                {
                    return _rarcInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rArc item info.
            /// </summary>
            [RepositoryItemInfo("0ac9611d-31d2-4764-802c-1e47284a334a")]
            public virtual RepoItemInfo rArcInfo
            {
                get
                {
                    return _rarcInfo;
                }
            }

            /// <summary>
            /// The rPressure item.
            /// </summary>
            [RepositoryItem("9f54a3fa-0684-4cef-86f6-58c02cb35f83")]
            public virtual Ranorex.Text rPressure
            {
                get
                {
                    return _rpressureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rPressure item info.
            /// </summary>
            [RepositoryItemInfo("9f54a3fa-0684-4cef-86f6-58c02cb35f83")]
            public virtual RepoItemInfo rPressureInfo
            {
                get
                {
                    return _rpressureInfo;
                }
            }

            /// <summary>
            /// The rNumSprinklers item.
            /// </summary>
            [RepositoryItem("f270bdcd-4106-4eee-b92c-b8b5a7b913a7")]
            public virtual Ranorex.Text rNumSprinklers
            {
                get
                {
                    return _rnumsprinklersInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rNumSprinklers item info.
            /// </summary>
            [RepositoryItemInfo("f270bdcd-4106-4eee-b92c-b8b5a7b913a7")]
            public virtual RepoItemInfo rNumSprinklersInfo
            {
                get
                {
                    return _rnumsprinklersInfo;
                }
            }

            /// <summary>
            /// The rNozzleFlow item.
            /// </summary>
            [RepositoryItem("21354700-b26d-4efe-8fa4-702b4d6bd5d9")]
            public virtual Ranorex.Text rNozzleFlow
            {
                get
                {
                    return _rnozzleflowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rNozzleFlow item info.
            /// </summary>
            [RepositoryItemInfo("21354700-b26d-4efe-8fa4-702b4d6bd5d9")]
            public virtual RepoItemInfo rNozzleFlowInfo
            {
                get
                {
                    return _rnozzleflowInfo;
                }
            }

            /// <summary>
            /// The rBackFlow item.
            /// </summary>
            [RepositoryItem("7dc6ad49-f63e-411e-815c-3d9f58beaeaa")]
            public virtual Ranorex.Text rBackFlow
            {
                get
                {
                    return _rbackflowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rBackFlow item info.
            /// </summary>
            [RepositoryItemInfo("7dc6ad49-f63e-411e-815c-3d9f58beaeaa")]
            public virtual RepoItemInfo rBackFlowInfo
            {
                get
                {
                    return _rbackflowInfo;
                }
            }

            /// <summary>
            /// The rStaFlow item.
            /// </summary>
            [RepositoryItem("3a43408b-938d-4379-9b7f-375b0ca8e93f")]
            public virtual Ranorex.Text rStaFlow
            {
                get
                {
                    return _rstaflowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rStaFlow item info.
            /// </summary>
            [RepositoryItemInfo("3a43408b-938d-4379-9b7f-375b0ca8e93f")]
            public virtual RepoItemInfo rStaFlowInfo
            {
                get
                {
                    return _rstaflowInfo;
                }
            }

            /// <summary>
            /// The rPrecipRate item.
            /// </summary>
            [RepositoryItem("c765f2ad-47a6-4a61-84e2-0f474ae2f32a")]
            public virtual Ranorex.Text rPrecipRate
            {
                get
                {
                    return _rpreciprateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rPrecipRate item info.
            /// </summary>
            [RepositoryItemInfo("c765f2ad-47a6-4a61-84e2-0f474ae2f32a")]
            public virtual RepoItemInfo rPrecipRateInfo
            {
                get
                {
                    return _rpreciprateInfo;
                }
            }

            /// <summary>
            /// The rPattern item.
            /// </summary>
            [RepositoryItem("56b7ea5a-b999-402f-b862-4ab2e9849598")]
            public virtual Ranorex.ComboBox rPattern
            {
                get
                {
                    return _rpatternInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The rPattern item info.
            /// </summary>
            [RepositoryItemInfo("56b7ea5a-b999-402f-b862-4ab2e9849598")]
            public virtual RepoItemInfo rPatternInfo
            {
                get
                {
                    return _rpatternInfo;
                }
            }

            /// <summary>
            /// The rSprinklerSpacing item.
            /// </summary>
            [RepositoryItem("f120039d-2ced-4585-82dc-7f86d020c9a1")]
            public virtual Ranorex.Text rSprinklerSpacing
            {
                get
                {
                    return _rsprinklerspacingInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rSprinklerSpacing item info.
            /// </summary>
            [RepositoryItemInfo("f120039d-2ced-4585-82dc-7f86d020c9a1")]
            public virtual RepoItemInfo rSprinklerSpacingInfo
            {
                get
                {
                    return _rsprinklerspacingInfo;
                }
            }

            /// <summary>
            /// The rRowSpacing item.
            /// </summary>
            [RepositoryItem("a96d516f-0934-402b-abb4-f15ca99f5722")]
            public virtual Ranorex.Text rRowSpacing
            {
                get
                {
                    return _rrowspacingInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The rRowSpacing item info.
            /// </summary>
            [RepositoryItemInfo("a96d516f-0934-402b-abb4-f15ca99f5722")]
            public virtual RepoItemInfo rRowSpacingInfo
            {
                get
                {
                    return _rrowspacingInfo;
                }
            }
        }

        /// <summary>
        /// The CS_HubLevelFolder folder.
        /// </summary>
        [RepositoryFolder("b983c49d-58bb-4543-b266-de857dc45f86")]
        public partial class CS_HubLevelFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CS_HubLevel  folder.
            /// </summary>
            public CS_HubLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_HubLevel", "", parentFolder, 0, null, false, "b983c49d-58bb-4543-b266-de857dc45f86", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b983c49d-58bb-4543-b266-de857dc45f86")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CS_DBLevelFolder folder.
        /// </summary>
        [RepositoryFolder("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
        public partial class CS_DBLevelFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CS_DBLevel  folder.
            /// </summary>
            public CS_DBLevelFolder(RepoGenBaseFolder parentFolder) :
                    base("CS_DBLevel", "", parentFolder, 0, null, false, "ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad2c6c34-6045-4ce1-91f7-4ea2cfcef93e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FormMainAppFolder folder.
        /// </summary>
        [RepositoryFolder("f640f73a-3c69-4234-a594-c821f9927dae")]
        public partial class FormMainAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new FormMain  folder.
            /// </summary>
            public FormMainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain", "/form[@controlname='FormMain']", parentFolder, 30000, null, true, "f640f73a-3c69-4234-a594-c821f9927dae", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f640f73a-3c69-4234-a594-c821f9927dae")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f640f73a-3c69-4234-a594-c821f9927dae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
